# Generated by Django 2.2.12 on 2020-04-28 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path_info', models.CharField(max_length=1023)),
                ('browser_info', models.CharField(max_length=255)),
                ('request_data', models.CharField(max_length=2047)),
                ('method', models.CharField(max_length=6)),
                ('event_name', models.CharField(max_length=1023)),
                ('visited_by', models.CharField(max_length=255)),
                ('location_city', models.CharField(max_length=255)),
                ('location_region', models.CharField(max_length=255)),
                ('location_country', models.CharField(max_length=255)),
                ('ip_address', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
